{% set name = "titlecase" %}
{% set version = "2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/titlecase-{{ version }}.tar.gz
  sha256: 269293cae4b1fc12fdb21224819201a2ab4b97f3ea36b334f90804799b140902

build:
  number: 0
  noarch: python
  entry_points:
    - titlecase = titlecase.__init__:cmd
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
    - setuptools-scm >=3
  run:
    - python >=3.4
  run_constrained:
    - regex >=2020.4.4

test:
  imports:
    - titlecase
  commands:
    - pip check
    - titlecase --help
  requires:
    - pip

about:
  home: https://github.com/ppannuto/python-titlecase
  summary: Python Port of John Gruber's titlecase.pl
  license: MIT
  # License file manually packaged. See: https://github.com/ppannuto/python-titlecase/pull/71
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - brocksam
    - thewchan
